version: '3'
services:
  node1:
    image: cassandra
    container_name: cass-node1
    hostname: nodo1
    ports:
      - "9042:9042"
    environment:
      - "MAX_HEAP_SIZE=256M"
      - "HEAP_NEWSIZE=128M"
      - "CASSANDRA_SEEDS=node1,node2,node3"
      - "CASSANDRA_CLUSTER_NAME=ClusterMiguel"
      - "CASSANDRA_DC=datacenter1"
      - "CASSANDRA_RACK=rack1"
      - "CASSANDRA_AUTH_ENABLED=true"
      - "CASSANDRA_USERNAME=miguel"
      - "CASSANDRA_PASSWORD=123"

    restart: always
    volumes:
      - ./data/node1:/var/lib/cassandra
      - ./scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "cqlsh", "-u cassandra", "-p cassandra" ,"-e describe keyspaces"]
      interval: 15s
      timeout: 10s
      retries: 10

  node2:
    image: cassandra
    container_name: cass-node2
    hostname: nodo2
    ports:
      - "9043:9042"
    environment:
      - "MAX_HEAP_SIZE=256M"
      - "HEAP_NEWSIZE=128M"
      - "CASSANDRA_SEEDS=node1,node2,node3"
      - "CASSANDRA_CLUSTER_NAME=ClusterMiguel"
      - "CASSANDRA_DC=datacenter1"
      - "CASSANDRA_RACK=rack2"
      - "CASSANDRA_AUTH_ENABLED=true"

    restart: always
    volumes:
      - ./data/node2:/var/lib/cassandra
    healthcheck:
      test: ["CMD", "cqlsh", "-u cassandra", "-p cassandra" ,"-e describe keyspaces"]
      interval: 15s
      timeout: 10s
      retries: 10

  node3:
    image: cassandra
    container_name: cass-node3
    hostname: nodo3
    ports:
      - "9044:9042"
    environment:
      - "MAX_HEAP_SIZE=256M"
      - "HEAP_NEWSIZE=128M"
      - "CASSANDRA_SEEDS=node1,node2,node3"
      - "CASSANDRA_CLUSTER_NAME=ClusterMiguel"
      - "CASSANDRA_DC=datacenter1"
      - "CASSANDRA_RACK=rack3"
      - "CASSANDRA_AUTH_ENABLED=true"

    restart: always
    volumes:
      - ./data/node3:/var/lib/cassandra
    healthcheck:
      test: ["CMD", "cqlsh", "-u cassandra", "-p cassandra" ,"-e describe keyspaces"]
      interval: 15s
      timeout: 10s
      retries: 10

  cassandra-keyspace:
    container_name: cassandra-keyspace
    image: cassandra:latest
    depends_on:
      node1:
        condition: service_healthy
      node2:
        condition: service_healthy
      node3:
        condition: service_healthy
    volumes:
      - ./scripts/createKeyspaceAndTable.cql:/docker-entrypoint-initdb.d/createKeyspaceAndTable.cql
      - ./scripts/initAll.sh:/docker-entrypoint-initdb.d/initAll.sh
    command: /bin/bash -c "/docker-entrypoint-initdb.d/initAll.sh"
